# Generated by Django 3.0.6 on 2020-05-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
        migrations.AlterField(
            model_name='introandprofilepic',
            name='profile_pic',
            field=models.FileField(upload_to='user/images/profilepic/'),
        ),
        migrations.AlterField(
            model_name='languagestools',
            name='logo',
            field=models.FileField(upload_to='user/images/languages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='user/images/projects/'),
        ),
    ]
